# Generated by Django 5.0.6 on 2024-05-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
    ]
